spring:
  application:
    name: Picple

#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: update # create: ?? ? ?? ??? ??, ?? ??? ?? ?? / update: ?? ? ?? ??? ??, ??? ?? ????
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace # ??? ? Hibernate? SQL ?? ????? ???? ??? ?? ??? ??